### PR TITLE
Change naming convention for appliance

### PR DESCRIPTION
**Pull request by andreabolognani**
If this is considered a good direction, I will prepare a PR that adjusts the CI jobs accordingly.

### CODE REVIEW

**Comment by alicefr** [comment]
@andreabolognani I'd be fine by changing the name, but... :) We need a way to deprecate and remove old appliances in the google store. I don't want that we run out-of-space because of the weekly CI job for the appliance. I don't recall how this work, but before merging this we need to clarify it.
I'm aware that I was relying on the same versioning and overwriting with new builds, and this needs to be changed!

UPDATE: Additionally, we need to understand which versions of the appliance are used and which are not. Otherwise, if we remove them the build will fail when it tries to download the appliance.

**Comment by andreabolognani** [comment]
> @andreabolognani I'd be fine by changing the name, but... :) We need a way to deprecate and remove old appliances in the google store. I don't want that we run out-of-space because of the weekly CI job for the appliance. I don't recall how this work, but before merging this we need to clarify it. I'm aware that I was relying on the same versioning and overwriting with new builds, and this needs to be changed!

That's a good point. I guess we could perform this cleanup as part of the same weekly CI job, or another one with a similar schedule. Once we have the timestamp included in the filename, it should be easy to implement a cleanup policy like "only keep the five most recent builds".

> UPDATE: Additionally, we need to understand which versions of the appliance are used and which are not. Otherwise, if we remove them the build will fail when it tries to download the appliance.

I wonder if we could just clone `kubevirt.git` on the fly and the run something like

```
git log -p WORKSPACE | grep appliance- | grep ^+
```

to find out which versions have been used in KubeVirt and should thus not be removed. Not the fastest method, but should give accurate results without need for maintenance.

**Comment by alicefr** [comment]
> > @andreabolognani I'd be fine by changing the name, but... :) We need a way to deprecate and remove old appliances in the google store. I don't want that we run out-of-space because of the weekly CI job for the appliance. I don't recall how this work, but before merging this we need to clarify it. I'm aware that I was relying on the same versioning and overwriting with new builds, and this needs to be changed!
> 
> That's a good point. I guess we could perform this cleanup as part of the same weekly CI job, or another one with a similar schedule. Once we have the timestamp included in the filename, it should be easy to implement a cleanup policy like "only keep the five most recent builds".
> 

We should have a similar mechanism for the rpms, and I'd like to rely on the same process. I asked @brianmcarey to help me finding how we handle the rpm repository. 
We need to take into account that we also have old branches where we do backports. I don't think we can only keep the last five most recent builds. We would also need to periodically update the KubeVirt WORKSPACE and this isn't currently the case.

> > UPDATE: Additionally, we need to understand which versions of the appliance are used and which are not. Otherwise, if we remove them the build will fail when it tries to download the appliance.
> 
> I wonder if we could just clone `kubevirt.git` on the fly and the run something like
> 
> ```
> git log -p WORKSPACE | grep appliance- | grep ^+
> ```
> 
> to find out which versions have been used in KubeVirt and should thus not be removed. Not the fastest method, but should give accurate results without need for maintenance.

As already mentioned, we need to take into account also old branches. So, probably yes but with a list of branches where we actively develop and apply fixes.

**Comment by andreabolognani** [comment]
> We should have a similar mechanism for the rpms, and I'd like to rely on the same process. I asked @brianmcarey to help me finding how we handle the rpm repository.

I think the process is not the same, because the mirroring of RPMs happens as a consequence of the WORKSPACE being updated, so by definition all of those need to be kept around. For the appliance, we do weekly builds and not all of those are picked up by KubeVirt.

> We need to take into account that we also have old branches where we do backports.

Aren't the backports just cherry-picks of commits from the main branch? So if an appliance was never used on main, it won't be used on any maintenance branch either.

> I don't think we can only keep the last five most recent builds.

I was thinking of the last five builds *among those that are not used in KubeVirt*. If any of the builds was ever referenced by KubeVirt, then we'd need to keep it around.

> We would also need to periodically update the KubeVirt WORKSPACE and this isn't currently the case.

I guess you could set up a way for PRs to automatically be opened against KubeVirt, but I was not thinking that far ahead O:-)

I just assumed that having KubeVirt pick up a new version of the appliance would be a manual affair, same as picking up updated RPMs currently is.

**Comment by alicefr** [comment]
> > We should have a similar mechanism for the rpms, and I'd like to rely on the same process. I asked @brianmcarey to help me finding how we handle the rpm repository.
> 
> I think the process is not the same, because the mirroring of RPMs happens as a consequence of the WORKSPACE being updated, so by definition all of those need to be kept around. For the appliance, we do weekly builds and not all of those are picked up by KubeVirt.
> 

You are right about the copy and update. But I don't know how they remove the old rpms once they aren't used anymore. I'd be interested to understand how they clean-up the old versions. 

> > We need to take into account that we also have old branches where we do backports.
> 
> Aren't the backports just cherry-picks of commits from the main branch? So if an appliance was never used on main, it won't be used on any maintenance branch either.
> 

Correct, we can remove appliances that were never picked. But we need to consider that different branches might have different appliance versions.

> > I don't think we can only keep the last five most recent builds.
> 
> I was thinking of the last five builds _among those that are not used in KubeVirt_. If any of the builds was ever referenced by KubeVirt, then we'd need to keep it around.
> 

Ok, still not quite sure where to store/get this information

> > We would also need to periodically update the KubeVirt WORKSPACE and this isn't currently the case.
> 
> I guess you could set up a way for PRs to automatically be opened against KubeVirt, but I was not thinking that far ahead O:-)
> 
> I just assumed that having KubeVirt pick up a new version of the appliance would be a manual affair, same as picking up updated RPMs currently is.

Ok, yes and I'd like to keep it this way if possible :)

**Pull request closed without merging**
